// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: rental.proto

package rental_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rental struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId             string `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	BookName           string `protobuf:"bytes,3,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
	UserId             string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RentalDateTime     string `protobuf:"bytes,5,opt,name=rental_date_time,json=rentalDateTime,proto3" json:"rental_date_time,omitempty"`
	ExpectedReturnDate string `protobuf:"bytes,6,opt,name=expected_return_date,json=expectedReturnDate,proto3" json:"expected_return_date,omitempty"`
	ReturnDate         string `protobuf:"bytes,7,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
	BookFines          string `protobuf:"bytes,8,opt,name=book_fines,json=bookFines,proto3" json:"book_fines,omitempty"`
	RentalStatus       string `protobuf:"bytes,9,opt,name=rental_status,json=rentalStatus,proto3" json:"rental_status,omitempty"`
}

func (x *Rental) Reset() {
	*x = Rental{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rental_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rental) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rental) ProtoMessage() {}

func (x *Rental) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rental.ProtoReflect.Descriptor instead.
func (*Rental) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{0}
}

func (x *Rental) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rental) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *Rental) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

func (x *Rental) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Rental) GetRentalDateTime() string {
	if x != nil {
		return x.RentalDateTime
	}
	return ""
}

func (x *Rental) GetExpectedReturnDate() string {
	if x != nil {
		return x.ExpectedReturnDate
	}
	return ""
}

func (x *Rental) GetReturnDate() string {
	if x != nil {
		return x.ReturnDate
	}
	return ""
}

func (x *Rental) GetBookFines() string {
	if x != nil {
		return x.BookFines
	}
	return ""
}

func (x *Rental) GetRentalStatus() string {
	if x != nil {
		return x.RentalStatus
	}
	return ""
}

type CreateRentalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookId             string `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	BookName           string `protobuf:"bytes,2,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
	UserId             string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpectedReturnDate string `protobuf:"bytes,4,opt,name=expected_return_date,json=expectedReturnDate,proto3" json:"expected_return_date,omitempty"`
}

func (x *CreateRentalRequest) Reset() {
	*x = CreateRentalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rental_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRentalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRentalRequest) ProtoMessage() {}

func (x *CreateRentalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRentalRequest.ProtoReflect.Descriptor instead.
func (*CreateRentalRequest) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRentalRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *CreateRentalRequest) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

func (x *CreateRentalRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateRentalRequest) GetExpectedReturnDate() string {
	if x != nil {
		return x.ExpectedReturnDate
	}
	return ""
}

type GetRentalListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  int32  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Search string `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
}

func (x *GetRentalListRequest) Reset() {
	*x = GetRentalListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rental_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRentalListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRentalListRequest) ProtoMessage() {}

func (x *GetRentalListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRentalListRequest.ProtoReflect.Descriptor instead.
func (*GetRentalListRequest) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{2}
}

func (x *GetRentalListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetRentalListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetRentalListRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type GetRentalListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rentals []*Rental `protobuf:"bytes,1,rep,name=rentals,proto3" json:"rentals,omitempty"`
}

func (x *GetRentalListResponse) Reset() {
	*x = GetRentalListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rental_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRentalListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRentalListResponse) ProtoMessage() {}

func (x *GetRentalListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRentalListResponse.ProtoReflect.Descriptor instead.
func (*GetRentalListResponse) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{3}
}

func (x *GetRentalListResponse) GetRentals() []*Rental {
	if x != nil {
		return x.Rentals
	}
	return nil
}

type GetRentalByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRentalByIdRequest) Reset() {
	*x = GetRentalByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rental_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRentalByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRentalByIdRequest) ProtoMessage() {}

func (x *GetRentalByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRentalByIdRequest.ProtoReflect.Descriptor instead.
func (*GetRentalByIdRequest) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{4}
}

func (x *GetRentalByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateRentalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId       string `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	BookName     string `protobuf:"bytes,3,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
	UserId       string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookFines    string `protobuf:"bytes,5,opt,name=book_fines,json=bookFines,proto3" json:"book_fines,omitempty"`
	RentalStatus string `protobuf:"bytes,6,opt,name=rental_status,json=rentalStatus,proto3" json:"rental_status,omitempty"`
}

func (x *UpdateRentalRequest) Reset() {
	*x = UpdateRentalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rental_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRentalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRentalRequest) ProtoMessage() {}

func (x *UpdateRentalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRentalRequest.ProtoReflect.Descriptor instead.
func (*UpdateRentalRequest) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRentalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRentalRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *UpdateRentalRequest) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

func (x *UpdateRentalRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateRentalRequest) GetBookFines() string {
	if x != nil {
		return x.BookFines
	}
	return ""
}

func (x *UpdateRentalRequest) GetRentalStatus() string {
	if x != nil {
		return x.RentalStatus
	}
	return ""
}

type DeleteRentalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RentalStatus string `protobuf:"bytes,2,opt,name=rental_status,json=rentalStatus,proto3" json:"rental_status,omitempty"`
}

func (x *DeleteRentalRequest) Reset() {
	*x = DeleteRentalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rental_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRentalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRentalRequest) ProtoMessage() {}

func (x *DeleteRentalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRentalRequest.ProtoReflect.Descriptor instead.
func (*DeleteRentalRequest) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRentalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRentalRequest) GetRentalStatus() string {
	if x != nil {
		return x.RentalStatus
	}
	return ""
}

type DeleteRentalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RentalStatus string `protobuf:"bytes,1,opt,name=rental_status,json=rentalStatus,proto3" json:"rental_status,omitempty"`
}

func (x *DeleteRentalResponse) Reset() {
	*x = DeleteRentalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rental_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRentalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRentalResponse) ProtoMessage() {}

func (x *DeleteRentalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRentalResponse.ProtoReflect.Descriptor instead.
func (*DeleteRentalResponse) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRentalResponse) GetRentalStatus() string {
	if x != nil {
		return x.RentalStatus
	}
	return ""
}

var File_rental_proto protoreflect.FileDescriptor

var file_rental_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8,
	0x02, 0x0a, 0x06, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x6f, 0x6f,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x72, 0x65, 0x6e, 0x74,
	0x61, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x72,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x12, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x44, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x66, 0x69,
	0x6e, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x46,
	0x69, 0x6e, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x96, 0x01, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f,
	0x6f, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62,
	0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x30, 0x0a, 0x14, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12,
	0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x44, 0x61,
	0x74, 0x65, 0x22, 0x5c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x22, 0x3a, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x07, 0x72, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x52, 0x07, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x73, 0x22, 0x26, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0xb8, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x6e, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62,
	0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x62,
	0x6f, 0x6f, 0x6b, 0x5f, 0x66, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x46, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65,
	0x6e, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x4a, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72,
	0x65, 0x6e, 0x74, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3b, 0x0a, 0x14, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x6e, 0x74,
	0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xa5, 0x02, 0x0a, 0x0d, 0x52, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x0c, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x12, 0x14, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x07, 0x2e, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x12, 0x15,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x07, 0x2e, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x22, 0x00,
	0x12, 0x2f, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c,
	0x12, 0x14, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x07, 0x2e, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x22,
	0x00, 0x12, 0x3d, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6e, 0x74, 0x61,
	0x6c, 0x12, 0x14, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x72, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rental_proto_rawDescOnce sync.Once
	file_rental_proto_rawDescData = file_rental_proto_rawDesc
)

func file_rental_proto_rawDescGZIP() []byte {
	file_rental_proto_rawDescOnce.Do(func() {
		file_rental_proto_rawDescData = protoimpl.X.CompressGZIP(file_rental_proto_rawDescData)
	})
	return file_rental_proto_rawDescData
}

var file_rental_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rental_proto_goTypes = []interface{}{
	(*Rental)(nil),                // 0: Rental
	(*CreateRentalRequest)(nil),   // 1: CreateRentalRequest
	(*GetRentalListRequest)(nil),  // 2: GetRentalListRequest
	(*GetRentalListResponse)(nil), // 3: GetRentalListResponse
	(*GetRentalByIdRequest)(nil),  // 4: GetRentalByIdRequest
	(*UpdateRentalRequest)(nil),   // 5: UpdateRentalRequest
	(*DeleteRentalRequest)(nil),   // 6: DeleteRentalRequest
	(*DeleteRentalResponse)(nil),  // 7: DeleteRentalResponse
}
var file_rental_proto_depIdxs = []int32{
	0, // 0: GetRentalListResponse.rentals:type_name -> Rental
	1, // 1: RentalService.CreateRental:input_type -> CreateRentalRequest
	2, // 2: RentalService.GetRentalList:input_type -> GetRentalListRequest
	4, // 3: RentalService.GetRentalById:input_type -> GetRentalByIdRequest
	5, // 4: RentalService.UpdateRental:input_type -> UpdateRentalRequest
	6, // 5: RentalService.DeleteRental:input_type -> DeleteRentalRequest
	0, // 6: RentalService.CreateRental:output_type -> Rental
	3, // 7: RentalService.GetRentalList:output_type -> GetRentalListResponse
	0, // 8: RentalService.GetRentalById:output_type -> Rental
	0, // 9: RentalService.UpdateRental:output_type -> Rental
	7, // 10: RentalService.DeleteRental:output_type -> DeleteRentalResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rental_proto_init() }
func file_rental_proto_init() {
	if File_rental_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rental_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rental); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rental_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRentalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rental_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRentalListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rental_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRentalListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rental_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRentalByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rental_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRentalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rental_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRentalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rental_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRentalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rental_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rental_proto_goTypes,
		DependencyIndexes: file_rental_proto_depIdxs,
		MessageInfos:      file_rental_proto_msgTypes,
	}.Build()
	File_rental_proto = out.File
	file_rental_proto_rawDesc = nil
	file_rental_proto_goTypes = nil
	file_rental_proto_depIdxs = nil
}
